######################################################################
##
## Filename: single_cycle_core.udo
## Created on: Fri Apr 13 10:49:35 PM AUS Eastern Standard Time 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
